version: '3'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: on-failure
    ports:
      - 7080:8080

  server:
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: on-failure
    environment:
      MONGO_URI: mongodb://salamantos:RucKwFpYFAQmrO4mWwth@mongo:27017
    depends_on:
      - mongo
    ports:
      - 7001:8001

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: salamantos
      MONGO_INITDB_ROOT_PASSWORD: RucKwFpYFAQmrO4mWwth

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 7081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: salamantos
      ME_CONFIG_MONGODB_ADMINPASSWORD: RucKwFpYFAQmrO4mWwth
      ME_CONFIG_MONGODB_URL: mongodb://salamantos:RucKwFpYFAQmrO4mWwth@mongo:27017/
